port 26379
daemonize yes
pidfile /var/run/redis-sentinel.pid
logfile /var/log/redis-sentinel.log
dir /tmp

# 监控主节点
sentinel monitor mymaster 10.0.0.254 6379 2

# 主观下线时间（毫秒）
sentinel down-after-milliseconds mymaster 5000

# 故障转移超时时间（毫秒）
sentinel failover-timeout mymaster 60000

# 同步复制数量
sentinel parallel-syncs mymaster 1

# 从节点配置
sentinel known-replica mymaster 10.0.0.1 6379
sentinel known-replica mymaster 10.0.0.2 6379
